package co.loystar.loystarbusiness.models.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import co.loystar.loystarbusiness.models.db.DBTransaction;
import co.loystar.loystarbusiness.models.db.DBSubscription;
import co.loystar.loystarbusiness.models.db.DBMerchantLoyaltyProgram;
import co.loystar.loystarbusiness.models.db.DBBirthdayOffer;
import co.loystar.loystarbusiness.models.db.DBBirthdayOfferPresetSMS;
import co.loystar.loystarbusiness.models.db.DBProduct;
import co.loystar.loystarbusiness.models.db.DBCustomer;
import co.loystar.loystarbusiness.models.db.DBConfig;
import co.loystar.loystarbusiness.models.db.DBMerchant;
import co.loystar.loystarbusiness.models.db.DBProductCategory;

import co.loystar.loystarbusiness.models.db.DBTransactionDao;
import co.loystar.loystarbusiness.models.db.DBSubscriptionDao;
import co.loystar.loystarbusiness.models.db.DBMerchantLoyaltyProgramDao;
import co.loystar.loystarbusiness.models.db.DBBirthdayOfferDao;
import co.loystar.loystarbusiness.models.db.DBBirthdayOfferPresetSMSDao;
import co.loystar.loystarbusiness.models.db.DBProductDao;
import co.loystar.loystarbusiness.models.db.DBCustomerDao;
import co.loystar.loystarbusiness.models.db.DBConfigDao;
import co.loystar.loystarbusiness.models.db.DBMerchantDao;
import co.loystar.loystarbusiness.models.db.DBProductCategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTransactionDaoConfig;
    private final DaoConfig dBSubscriptionDaoConfig;
    private final DaoConfig dBMerchantLoyaltyProgramDaoConfig;
    private final DaoConfig dBBirthdayOfferDaoConfig;
    private final DaoConfig dBBirthdayOfferPresetSMSDaoConfig;
    private final DaoConfig dBProductDaoConfig;
    private final DaoConfig dBCustomerDaoConfig;
    private final DaoConfig dBConfigDaoConfig;
    private final DaoConfig dBMerchantDaoConfig;
    private final DaoConfig dBProductCategoryDaoConfig;

    private final DBTransactionDao dBTransactionDao;
    private final DBSubscriptionDao dBSubscriptionDao;
    private final DBMerchantLoyaltyProgramDao dBMerchantLoyaltyProgramDao;
    private final DBBirthdayOfferDao dBBirthdayOfferDao;
    private final DBBirthdayOfferPresetSMSDao dBBirthdayOfferPresetSMSDao;
    private final DBProductDao dBProductDao;
    private final DBCustomerDao dBCustomerDao;
    private final DBConfigDao dBConfigDao;
    private final DBMerchantDao dBMerchantDao;
    private final DBProductCategoryDao dBProductCategoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTransactionDaoConfig = daoConfigMap.get(DBTransactionDao.class).clone();
        dBTransactionDaoConfig.initIdentityScope(type);

        dBSubscriptionDaoConfig = daoConfigMap.get(DBSubscriptionDao.class).clone();
        dBSubscriptionDaoConfig.initIdentityScope(type);

        dBMerchantLoyaltyProgramDaoConfig = daoConfigMap.get(DBMerchantLoyaltyProgramDao.class).clone();
        dBMerchantLoyaltyProgramDaoConfig.initIdentityScope(type);

        dBBirthdayOfferDaoConfig = daoConfigMap.get(DBBirthdayOfferDao.class).clone();
        dBBirthdayOfferDaoConfig.initIdentityScope(type);

        dBBirthdayOfferPresetSMSDaoConfig = daoConfigMap.get(DBBirthdayOfferPresetSMSDao.class).clone();
        dBBirthdayOfferPresetSMSDaoConfig.initIdentityScope(type);

        dBProductDaoConfig = daoConfigMap.get(DBProductDao.class).clone();
        dBProductDaoConfig.initIdentityScope(type);

        dBCustomerDaoConfig = daoConfigMap.get(DBCustomerDao.class).clone();
        dBCustomerDaoConfig.initIdentityScope(type);

        dBConfigDaoConfig = daoConfigMap.get(DBConfigDao.class).clone();
        dBConfigDaoConfig.initIdentityScope(type);

        dBMerchantDaoConfig = daoConfigMap.get(DBMerchantDao.class).clone();
        dBMerchantDaoConfig.initIdentityScope(type);

        dBProductCategoryDaoConfig = daoConfigMap.get(DBProductCategoryDao.class).clone();
        dBProductCategoryDaoConfig.initIdentityScope(type);

        dBTransactionDao = new DBTransactionDao(dBTransactionDaoConfig, this);
        dBSubscriptionDao = new DBSubscriptionDao(dBSubscriptionDaoConfig, this);
        dBMerchantLoyaltyProgramDao = new DBMerchantLoyaltyProgramDao(dBMerchantLoyaltyProgramDaoConfig, this);
        dBBirthdayOfferDao = new DBBirthdayOfferDao(dBBirthdayOfferDaoConfig, this);
        dBBirthdayOfferPresetSMSDao = new DBBirthdayOfferPresetSMSDao(dBBirthdayOfferPresetSMSDaoConfig, this);
        dBProductDao = new DBProductDao(dBProductDaoConfig, this);
        dBCustomerDao = new DBCustomerDao(dBCustomerDaoConfig, this);
        dBConfigDao = new DBConfigDao(dBConfigDaoConfig, this);
        dBMerchantDao = new DBMerchantDao(dBMerchantDaoConfig, this);
        dBProductCategoryDao = new DBProductCategoryDao(dBProductCategoryDaoConfig, this);

        registerDao(DBTransaction.class, dBTransactionDao);
        registerDao(DBSubscription.class, dBSubscriptionDao);
        registerDao(DBMerchantLoyaltyProgram.class, dBMerchantLoyaltyProgramDao);
        registerDao(DBBirthdayOffer.class, dBBirthdayOfferDao);
        registerDao(DBBirthdayOfferPresetSMS.class, dBBirthdayOfferPresetSMSDao);
        registerDao(DBProduct.class, dBProductDao);
        registerDao(DBCustomer.class, dBCustomerDao);
        registerDao(DBConfig.class, dBConfigDao);
        registerDao(DBMerchant.class, dBMerchantDao);
        registerDao(DBProductCategory.class, dBProductCategoryDao);
    }
    
    public void clear() {
        dBTransactionDaoConfig.clearIdentityScope();
        dBSubscriptionDaoConfig.clearIdentityScope();
        dBMerchantLoyaltyProgramDaoConfig.clearIdentityScope();
        dBBirthdayOfferDaoConfig.clearIdentityScope();
        dBBirthdayOfferPresetSMSDaoConfig.clearIdentityScope();
        dBProductDaoConfig.clearIdentityScope();
        dBCustomerDaoConfig.clearIdentityScope();
        dBConfigDaoConfig.clearIdentityScope();
        dBMerchantDaoConfig.clearIdentityScope();
        dBProductCategoryDaoConfig.clearIdentityScope();
    }

    public DBTransactionDao getDBTransactionDao() {
        return dBTransactionDao;
    }

    public DBSubscriptionDao getDBSubscriptionDao() {
        return dBSubscriptionDao;
    }

    public DBMerchantLoyaltyProgramDao getDBMerchantLoyaltyProgramDao() {
        return dBMerchantLoyaltyProgramDao;
    }

    public DBBirthdayOfferDao getDBBirthdayOfferDao() {
        return dBBirthdayOfferDao;
    }

    public DBBirthdayOfferPresetSMSDao getDBBirthdayOfferPresetSMSDao() {
        return dBBirthdayOfferPresetSMSDao;
    }

    public DBProductDao getDBProductDao() {
        return dBProductDao;
    }

    public DBCustomerDao getDBCustomerDao() {
        return dBCustomerDao;
    }

    public DBConfigDao getDBConfigDao() {
        return dBConfigDao;
    }

    public DBMerchantDao getDBMerchantDao() {
        return dBMerchantDao;
    }

    public DBProductCategoryDao getDBProductCategoryDao() {
        return dBProductCategoryDao;
    }

}
