package co.loystar.loystarbusiness.models.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBBIRTHDAY_OFFER".
*/
public class DBBirthdayOfferDao extends AbstractDao<DBBirthdayOffer, Long> {

    public static final String TABLENAME = "DBBIRTHDAY_OFFER";

    /**
     * Properties of entity DBBirthdayOffer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Merchant_id = new Property(1, Long.class, "merchant_id", false, "MERCHANT_ID");
        public final static Property Created_at = new Property(2, java.util.Date.class, "created_at", false, "CREATED_AT");
        public final static Property Updated_at = new Property(3, java.util.Date.class, "updated_at", false, "UPDATED_AT");
        public final static Property Local_db_created_at = new Property(4, java.util.Date.class, "local_db_created_at", false, "LOCAL_DB_CREATED_AT");
        public final static Property Local_db_updated_at = new Property(5, java.util.Date.class, "local_db_updated_at", false, "LOCAL_DB_UPDATED_AT");
        public final static Property Offer_description = new Property(6, String.class, "offer_description", false, "OFFER_DESCRIPTION");
        public final static Property Synced = new Property(7, Integer.class, "synced", false, "SYNCED");
        public final static Property Deleted = new Property(8, Boolean.class, "deleted", false, "DELETED");
    }


    public DBBirthdayOfferDao(DaoConfig config) {
        super(config);
    }
    
    public DBBirthdayOfferDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBBIRTHDAY_OFFER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MERCHANT_ID\" INTEGER," + // 1: merchant_id
                "\"CREATED_AT\" INTEGER," + // 2: created_at
                "\"UPDATED_AT\" INTEGER," + // 3: updated_at
                "\"LOCAL_DB_CREATED_AT\" INTEGER," + // 4: local_db_created_at
                "\"LOCAL_DB_UPDATED_AT\" INTEGER," + // 5: local_db_updated_at
                "\"OFFER_DESCRIPTION\" TEXT," + // 6: offer_description
                "\"SYNCED\" INTEGER," + // 7: synced
                "\"DELETED\" INTEGER);"); // 8: deleted
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBBIRTHDAY_OFFER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBBirthdayOffer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long merchant_id = entity.getMerchant_id();
        if (merchant_id != null) {
            stmt.bindLong(2, merchant_id);
        }
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(3, created_at.getTime());
        }
 
        java.util.Date updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindLong(4, updated_at.getTime());
        }
 
        java.util.Date local_db_created_at = entity.getLocal_db_created_at();
        if (local_db_created_at != null) {
            stmt.bindLong(5, local_db_created_at.getTime());
        }
 
        java.util.Date local_db_updated_at = entity.getLocal_db_updated_at();
        if (local_db_updated_at != null) {
            stmt.bindLong(6, local_db_updated_at.getTime());
        }
 
        String offer_description = entity.getOffer_description();
        if (offer_description != null) {
            stmt.bindString(7, offer_description);
        }
 
        Integer synced = entity.getSynced();
        if (synced != null) {
            stmt.bindLong(8, synced);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(9, deleted ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBBirthdayOffer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long merchant_id = entity.getMerchant_id();
        if (merchant_id != null) {
            stmt.bindLong(2, merchant_id);
        }
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(3, created_at.getTime());
        }
 
        java.util.Date updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindLong(4, updated_at.getTime());
        }
 
        java.util.Date local_db_created_at = entity.getLocal_db_created_at();
        if (local_db_created_at != null) {
            stmt.bindLong(5, local_db_created_at.getTime());
        }
 
        java.util.Date local_db_updated_at = entity.getLocal_db_updated_at();
        if (local_db_updated_at != null) {
            stmt.bindLong(6, local_db_updated_at.getTime());
        }
 
        String offer_description = entity.getOffer_description();
        if (offer_description != null) {
            stmt.bindString(7, offer_description);
        }
 
        Integer synced = entity.getSynced();
        if (synced != null) {
            stmt.bindLong(8, synced);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(9, deleted ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBBirthdayOffer readEntity(Cursor cursor, int offset) {
        DBBirthdayOffer entity = new DBBirthdayOffer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // merchant_id
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // created_at
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // updated_at
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // local_db_created_at
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // local_db_updated_at
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // offer_description
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // synced
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0 // deleted
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBBirthdayOffer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMerchant_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCreated_at(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdated_at(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setLocal_db_created_at(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setLocal_db_updated_at(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setOffer_description(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSynced(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setDeleted(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBBirthdayOffer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBBirthdayOffer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBBirthdayOffer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
